# This file was generated by GoReleaser. DO NOT EDIT.
cask "risor" do
  version "2.2.0"

  on_macos do
    on_intel do
      url "https://github.com/deepnoodle-ai/risor/releases/download/v#{version}/risor_Darwin_x86_64.tar.gz",
        verified: "github.com/deepnoodle-ai/risor/"
      sha256 "c7dd2925c504f237015948e0e8d0155c43e03735a3f1b31eabf171c5bb2b45a5"
    end
    on_arm do
      url "https://github.com/deepnoodle-ai/risor/releases/download/v#{version}/risor_Darwin_arm64.tar.gz",
        verified: "github.com/deepnoodle-ai/risor/"
      sha256 "269d9eb7197e4923190f00fadf6392f75095f26febcd92785f753399d1b8577e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/deepnoodle-ai/risor/releases/download/v#{version}/risor_Linux_x86_64.tar.gz",
        verified: "github.com/deepnoodle-ai/risor/"
      sha256 "dbf6201afc9d9b115cb663f48d00603ce67f156468a28df11e924057f6c1c68b"
    end
    on_arm do
      url "https://github.com/deepnoodle-ai/risor/releases/download/v#{version}/risor_Linux_arm64.tar.gz",
        verified: "github.com/deepnoodle-ai/risor/"
      sha256 "661edc1d3a01e448a6b7c08e23acf2e325f1ae1e044f8fe9dfdeb117324c1688"
    end
  end

  name "risor"
  desc "An embedded scripting language for Go projects"
  homepage "https://github.com/deepnoodle-ai/risor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "risor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/risor"]
    end
  end

  # No zap stanza required

end
