# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Risor < Formula
  desc "An embedded scripting language for Go projects"
  homepage "https://github.com/deepnoodle-ai/risor"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deepnoodle-ai/risor/releases/download/v2.0.0/risor_Darwin_x86_64.tar.gz"
      sha256 "5e3ddf1d8fb323f9f131f962fdabcd3f400b90bd6f68e922b718b47ecacd72f0"

      def install
        bin.install "risor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deepnoodle-ai/risor/releases/download/v2.0.0/risor_Darwin_arm64.tar.gz"
      sha256 "1cca44d1f04708275aaee09c871cff28c11aae5306da35538d1848b6a05dd5f8"

      def install
        bin.install "risor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deepnoodle-ai/risor/releases/download/v2.0.0/risor_Linux_x86_64.tar.gz"
      sha256 "ef8739cc5cb1b57bcaa966be92cac9792f993f290409138d3272e98b32d90b0a"
      def install
        bin.install "risor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deepnoodle-ai/risor/releases/download/v2.0.0/risor_Linux_arm64.tar.gz"
      sha256 "df1815deba0d632a8ebe829135b8a110b172d83074879cd96eb9cd39db3f83ae"
      def install
        bin.install "risor"
      end
    end
  end
end
